import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { makeStyles } from '@material-ui/core/styles'
import Button from '@material-ui/core/Button'
import LinkedInIcon from '@material-ui/icons/LinkedIn'
import GitHubIcon from '@material-ui/icons/GitHub'
import EmailIcon from '@material-ui/icons/Email'
import GitHub from '@material-ui/icons/GitHub'
import { motion } from 'framer-motion'

const useStyles = makeStyles({
    button: {
        /* backgroundImage: 'linear-gradient(45deg, #efc7d0, #aa4465)', */
        /* backgroundImage: 'linear-gradient(180deg, #efc7d0, #ff956e)', */
        backgroundColor: '#efc7d0',
        background: 'black',
        border: 0,
        borderRadius: 3,
        color: '#aa4465',
        height: 48,
        padding: '20px',
        margin: '10px',
    },
});

export default function Home() {

  const classes = useStyles();



  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main className={styles.main}>
        <h1 className={styles.title}>
          Constance Ingram
        </h1>
        <div className={styles.buttonbar}>
          <a href="https://www.linkedin.com/in/constance-ingram-7aa067161/" target="_blank"><LinkedInIcon fontSize="large" className={styles.icon}></LinkedInIcon></a>
          <a href="https://github.com/ccingram94" target="_blank"><GitHubIcon fontSize="large" className={styles.icon}></GitHubIcon></a>
          <a href="/contact" target="_blank"><EmailIcon fontSize="large" className={styles.icon}></EmailIcon></a>
        </div>
        <h2>
          Austin, TX
        </h2>
        <div className={styles.buttonbar}>
        <Button href="/resume" className={classes.button}>Resume</Button>
        <Button href="/projects" className={classes.button}>Projects</Button>
        <Button href="/contact" className={classes.button}>Contact</Button>
        </div>
      </motion.main>
      <footer>
      </footer>
    </div>
  )
}
