import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import { makeStyles } from '@material-ui/core/styles'
import Button from '@material-ui/core/Button'
import LinkedInIcon from '@material-ui/icons/LinkedIn'
import GitHubIcon from '@material-ui/icons/GitHub'
import EmailIcon from '@material-ui/icons/Email'
import GitHub from '@material-ui/icons/GitHub'
import { motion } from 'framer-motion'

const useStyles = makeStyles({
    button: {
        /* backgroundImage: 'linear-gradient(45deg, #efc7d0, #aa4465)', */
        /* backgroundImage: 'linear-gradient(180deg, #efc7d0, #ff956e)', */
        backgroundColor: '#efc7d0',
        background: 'black',
        border: 0,
        borderRadius: 3,
        color: '#aa4465',
        height: 48,
        padding: '20px',
        margin: '10px',
    },
});

export default function Home() {

  const classes = useStyles();

  return (
    <div className={styles.container}>
      <Head>
        <title>ConstanceIngram.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <motion.main className={styles.main}>
        <h1 className={styles.title}>
          Constance Ingram
        </h1>
        <div className={styles.buttonbar}>
          <Link href="https://www.linkedin.com/in/constance-ingram-7aa067161/"><LinkedInIcon fontSize="large" className={styles.icon}></LinkedInIcon></Link>
          <Link href="https://github.com/ccingram94"><GitHubIcon fontSize="large" className={styles.icon}></GitHubIcon></Link>
          <Link href="/contact"><EmailIcon fontSize="large" className={styles.icon}></EmailIcon></Link>
        </div>
        <h2>
          Austin, TX
        </h2>
        <div className={styles.buttonbar}>
        <Link href="/resume"><Button className={classes.button}>Resume</Button></Link>
        <Link href="/projects"><Button className={classes.button}>Projects</Button></Link>
        <Link href="/contact"><Button className={classes.button}>Contact</Button></Link>
        </div>
      </motion.main>
      <footer>
      </footer>
    </div>
  )
}
