import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Projects.module.css'
import { makeStyles } from '@material-ui/core/styles'
import Button from '@material-ui/core/Button'
import ArrowBackIosIcon from '@material-ui/icons/ArrowBackIos'
import Card from '@material-ui/core/Card'

const useStyles = makeStyles({
    button: {
        /* backgroundImage: 'linear-gradient(45deg, #efc7d0, #aa4465)', */
        /* backgroundImage: 'linear-gradient(180deg, #efc7d0, #ff956e)', */
        backgroundColor: '#efc7d0',
        background: 'black',
        border: 0,
        borderRadius: 3,
        color: '#aa4465',
        height: 48,
        padding: '20px',
        margin: '20px',
    },
});

export default function Projects() {

  const classes = useStyles();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <div className={styles.buttonbar}>
            <a href="/"><ArrowBackIosIcon fontSize="large" className={styles.icon}></ArrowBackIosIcon></a>
            <h1 className={styles.title}> Projects </h1>
          </div>
          <div className={styles.flexdisplay}>
            <Card className={styles.pagecard}>
              <h2>Aliens News</h2>
              <p>Next.js (React) || NewsAPI || Material-UI</p>
              <p><i>React webapp fetching JSON objects from NewsAPI and returning top headlines related to UFOs and extraterrestrials.</i></p>
              <Button className={classes.button}>Live Demo 🛸</Button>
            </Card>
            <Card className={styles.pagecard}>
              <h2>Giotto Tarot</h2>
              <p>Next.js (React) || PostgreSQL || Next-Auth || Prisma || Framer Motion </p>
              <p><i>Tarot application featuring animation with Framer Motion, user authentication with Next-Auth, artwork from the early Renaissance master Giotto, and a PostgreSQL database wrapped with Prisma ORM.</i></p>
              <Button className={classes.button}>Live Demo 🎴 </Button>
            </Card>
            <Card className={styles.pagecard}>
              <h2>React Tic-Tac-Toe</h2>
              <p>React || Cute CSS</p>
              <Button className={classes.button}> Live Demo 📚 </Button>
            </Card>
          </div>
      </main>
      <footer>
      </footer>
    </div>
  )
}
